# Generated by Django 2.2.6 on 2020-05-24 10:19

import burger.security.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Burguer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', help_text='Código do Hamburguer', max_length=20, verbose_name='Código')),
                ('name', models.CharField(default='', help_text='Nome do Hamburguer', max_length=40, verbose_name='Nome do Hamburguer')),
                ('description', models.CharField(default='', help_text='Descrição do Hamburger', max_length=500, verbose_name='Descrição do Hamburguer')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Preço do Hamburguer', max_digits=10, verbose_name='Preço')),
                ('discount', models.IntegerField(default=0, help_text='Desconto que será dada em (%) ao Hamburguer', verbose_name='Desconto(%)')),
                ('weight', models.DecimalField(decimal_places=0, default=0.0, help_text='Peso total do Hamburguer', max_digits=10, verbose_name='Peso')),
                ('energetic_value', models.DecimalField(decimal_places=0, default=0.0, help_text='Valor Energético', max_digits=10, verbose_name='Valor Energético')),
                ('point', models.IntegerField(choices=[(1, 'Mal Passado'), (2, 'No Ponto'), (3, 'Bem Passado')], default=2, help_text='Estado do Hamburguer', verbose_name='Estado do Hamburguer')),
                ('available', models.BooleanField(default=True, verbose_name='Ativo')),
                ('image_file', models.ImageField(default='', help_text='Imagem do hamburguer', upload_to='burgers', verbose_name='Imagem Principal')),
                ('hash_id', models.TextField(default='38313876-fc15-41f3-992e-f76d37fb96b8', unique=True)),
            ],
            options={
                'verbose_name': 'Burger',
                'db_table': 'bur_burguer',
            },
            bases=(models.Model, burger.security.models.PermissionLevelMixin),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(help_text='Comentário adicionado ao produto', max_length=200, verbose_name='Comentário')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Estrela que o produto recebeu', verbose_name='Estrelas')),
                ('burguer', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='burguer.Burguer')),
                ('user', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'db_table': 'rev_review',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(default='', help_text='Imagem do Hamburguer', upload_to='burgers', verbose_name='Imagem')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('burguer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='burguer.Burguer')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
                'db_table': 'pho_photo',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(help_text='Produto', max_length=200, verbose_name='Produto')),
                ('quantity', models.IntegerField(default=1, help_text='Quantidade do Item', verbose_name='Quantidade')),
                ('burguer', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='burguer.Burguer')),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
                'db_table': 'ing_ingredient',
            },
        ),
    ]
