# Generated by Django 2.2.6 on 2020-05-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burguer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burguer',
            name='hash_id',
            field=models.TextField(default='17894701-1875-4141-81f6-6f85ac71a9fd', unique=True),
        ),
    ]
