# Generated by Django 2.2.6 on 2020-07-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burguer', '0002_auto_20200524_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burguer',
            name='hash_id',
            field=models.TextField(default='180f0148-166a-4cc2-9c2b-54311777bf71', unique=True),
        ),
    ]
