# Generated by Django 2.2.6 on 2020-07-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burguer', '0003_auto_20200709_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burguer',
            name='hash_id',
            field=models.TextField(default='b2705775-6bec-49b5-b048-4e0d9d6fff93', unique=True),
        ),
    ]
