# Generated by Django 2.2.6 on 2020-07-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burguer', '0004_auto_20200709_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burguer',
            name='hash_id',
            field=models.TextField(default='6e1221bb-6bb9-43ea-8dbf-afbd96f55c29', unique=True),
        ),
    ]
