# Generated by Django 2.2.6 on 2020-07-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burguer', '0005_auto_20200709_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burguer',
            name='hash_id',
            field=models.TextField(default='903545e9-a884-410e-bbc6-13fe3ed6a3db', unique=True),
        ),
    ]
