# Generated by Django 2.2.6 on 2020-07-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burguer', '0007_auto_20200709_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burguer',
            name='hash_id',
            field=models.TextField(default='2de0b3d5-3fab-4d4b-874f-934a21fdaa40', unique=True),
        ),
    ]
