# Generated by Django 2.2.6 on 2020-07-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burguer', '0009_auto_20200716_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burguer',
            name='hash_id',
            field=models.TextField(default='171cd4ea-d027-4080-b39c-2225f2b6a628', unique=True),
        ),
    ]
