# Generated by Django 2.2.6 on 2020-07-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burguer', '0010_auto_20200716_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burguer',
            name='hash_id',
            field=models.TextField(default='380ec24a-bd7c-40b4-bdeb-67f7f8d7b746', unique=True),
        ),
    ]
