# Generated by Django 2.2.6 on 2020-07-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burguer', '0011_auto_20200716_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burguer',
            name='hash_id',
            field=models.TextField(default='ffdacb84-12ba-4be7-a093-15f9b6fd9ac2', unique=True),
        ),
    ]
