# Generated by Django 2.2.6 on 2020-07-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burguer', '0012_auto_20200716_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burguer',
            name='hash_id',
            field=models.TextField(default='cae2a300-d717-47db-a395-b100bb3a4e89', unique=True),
        ),
    ]
