# Generated by Django 2.2.6 on 2020-07-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burguer', '0013_auto_20200716_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burguer',
            name='hash_id',
            field=models.TextField(default='b10f937a-3a83-4bce-8441-14f0420fec77', unique=True),
        ),
    ]
