# Generated by Django 2.2.6 on 2020-07-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burguer', '0014_auto_20200716_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burguer',
            name='hash_id',
            field=models.TextField(default='b3ec6dd0-fa22-4131-952b-eb90a35dcd4b', unique=True),
        ),
    ]
