# Generated by Django 2.2.6 on 2020-07-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burguer', '0017_auto_20200716_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burguer',
            name='hash_id',
            field=models.TextField(default='a936560d-e96e-4f70-af3a-45b87d8406ad', unique=True),
        ),
    ]
