# Generated by Django 2.2.6 on 2020-07-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burguer', '0018_auto_20200716_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burguer',
            name='hash_id',
            field=models.TextField(default='97473009-d6da-4c48-a950-0e21f0c38fd5', unique=True),
        ),
    ]
