# Generated by Django 2.2.6 on 2020-07-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burguer', '0021_auto_20200729_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burguer',
            name='hash_id',
            field=models.TextField(default='9d085c6d-9a47-42e0-9da2-f819eebb9ec6', unique=True),
        ),
    ]
