# Generated by Django 2.2.6 on 2020-07-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burguer', '0023_auto_20200729_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burguer',
            name='hash_id',
            field=models.TextField(default='66d7a416-3213-4ac9-9326-c91ff31aa676', unique=True),
        ),
    ]
