# Generated by Django 2.2.6 on 2020-07-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topiccategory',
            name='identifier',
            field=models.CharField(choices=[(1, 'banner'), (2, 'slide'), (3, 'sorteio'), (4, 'sorteio-banner')], default='', max_length=255, verbose_name='Nome'),
        ),
    ]
