# Generated by Django 2.2.6 on 2020-07-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20200729_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topiccategory',
            name='identifier',
            field=models.CharField(choices=[('banner', 'banner'), ('slide', 'slide'), ('sorteio', 'sorteio'), ('sorteio-banner', 'sorteio-banner')], default='', max_length=255, verbose_name='Nome'),
        ),
    ]
