# Generated by Django 2.2.6 on 2020-05-24 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('processed', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, null=True)),
                ('traceback', models.TextField(blank=True, null=True)),
                ('context', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('resourcebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.ResourceBase')),
                ('start_date', models.DateTimeField(help_text='Data que inicia o oferta', null=True, verbose_name='Data de Inicio')),
                ('end_date', models.DateTimeField(help_text='Data que finaliza a oferta', null=True, verbose_name='Data do Fim')),
                ('title', models.CharField(default='', help_text='Titulo da oferta', max_length=40, verbose_name='Título da Oferta')),
                ('short_description', models.CharField(help_text='Pequeno resumo da oferta', max_length=500, verbose_name='Pequena Descrição')),
                ('image_file', models.ImageField(default='', help_text='Imagem da oferta que aparecera no site', upload_to='offers', verbose_name='Imagem da Oferta')),
                ('available', models.BooleanField(default=True, verbose_name='Ativo')),
                ('slug', models.SlugField(blank=True, default='')),
                ('hash_id', models.TextField(default='92b81986-4f37-4524-8e92-49016c0d35a1', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('upload_session', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offer.UploadSession')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
                'db_table': 'off_offer',
            },
            bases=('base.resourcebase',),
        ),
    ]
