# Generated by Django 2.2.6 on 2020-07-09 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_auto_20200709_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='hash_id',
            field=models.TextField(default='7f0b4cdd-5603-43a6-b718-5063da976462', unique=True),
        ),
        migrations.CreateModel(
            name='TicketRaffle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(default='42TNYI', unique=True)),
                ('active', models.BooleanField(default=True)),
                ('offer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offer.Offer')),
            ],
            options={
                'verbose_name': 'Cupom',
                'verbose_name_plural': 'Cupons',
                'db_table': 'tic_ticket',
            },
        ),
    ]
