# Generated by Django 2.2.6 on 2020-07-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_auto_20200709_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='hash_id',
            field=models.TextField(default='fb3efc87-e28d-46f9-9950-37c51dfbe9be', unique=True),
        ),
        migrations.AlterField(
            model_name='ticketraffle',
            name='code',
            field=models.TextField(default='3X3GR5', unique=True),
        ),
    ]
