# Generated by Django 2.2.6 on 2020-07-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0005_auto_20200709_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='hash_id',
            field=models.TextField(default='8940cec9-967b-4dc3-9f49-654675b4854a', unique=True),
        ),
        migrations.AlterField(
            model_name='ticketraffle',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticketraffle',
            name='code',
            field=models.TextField(default='3PQWVG', unique=True),
        ),
    ]
