# Generated by Django 2.2.6 on 2020-07-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0008_auto_20200716_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='hash_id',
            field=models.TextField(default='63eaf81f-acad-4528-ac41-0a82cc5037ad', unique=True),
        ),
        migrations.AlterField(
            model_name='ticketraffle',
            name='code',
            field=models.TextField(default='4MA9QX', unique=True),
        ),
    ]
