# Generated by Django 2.2.6 on 2020-07-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0012_auto_20200716_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='hash_id',
            field=models.TextField(default='03d7861d-f28b-4b56-b82c-5027e5556561', unique=True),
        ),
        migrations.AlterField(
            model_name='ticketraffle',
            name='code',
            field=models.TextField(default='3JDE23', unique=True),
        ),
    ]
