# Generated by Django 2.2.6 on 2020-07-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0013_auto_20200716_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='hash_id',
            field=models.TextField(default='8c740006-427d-48f7-b25a-a586c55e82a3', unique=True),
        ),
        migrations.AlterField(
            model_name='ticketraffle',
            name='code',
            field=models.TextField(default='JTMWGU', unique=True),
        ),
    ]
