# Generated by Django 2.2.6 on 2020-07-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0015_auto_20200716_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='hash_id',
            field=models.TextField(default='1c68d12b-26be-47cd-9249-3e2f952ac9f3', unique=True),
        ),
        migrations.AlterField(
            model_name='ticketraffle',
            name='code',
            field=models.TextField(default='MQMHVJ', unique=True),
        ),
    ]
