# Generated by Django 2.2.6 on 2020-07-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0016_auto_20200716_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='hash_id',
            field=models.TextField(default='b62a0a88-8121-48da-89f0-c8f44887d435', unique=True),
        ),
        migrations.AlterField(
            model_name='ticketraffle',
            name='code',
            field=models.TextField(default='4D5OZN', unique=True),
        ),
    ]
