# Generated by Django 2.2.6 on 2020-07-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0017_auto_20200716_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='hash_id',
            field=models.TextField(default='cd10b707-e5d4-40aa-90d1-6e89195a4686', unique=True),
        ),
        migrations.AlterField(
            model_name='ticketraffle',
            name='code',
            field=models.TextField(default='4FOJEK', unique=True),
        ),
    ]
