# Generated by Django 2.2.6 on 2020-07-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0018_auto_20200716_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='hash_id',
            field=models.TextField(default='0108de73-5128-41ad-bd40-5ccc2fe87ddb', unique=True),
        ),
        migrations.AlterField(
            model_name='ticketraffle',
            name='code',
            field=models.TextField(default='49YKS4', unique=True),
        ),
    ]
