# Generated by Django 2.2.6 on 2020-07-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0019_auto_20200716_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='hash_id',
            field=models.TextField(default='27b97ff7-d7fb-4402-85d3-180c889a8b0a', unique=True),
        ),
        migrations.AlterField(
            model_name='ticketraffle',
            name='code',
            field=models.TextField(default='SBEYBN', unique=True),
        ),
    ]
