# Generated by Django 2.2.6 on 2020-07-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0020_auto_20200729_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='hash_id',
            field=models.TextField(default='cc81dce9-1c1c-4a98-b0b6-646818e1686c', unique=True),
        ),
        migrations.AlterField(
            model_name='ticketraffle',
            name='code',
            field=models.TextField(default='3PGFQJ', unique=True),
        ),
    ]
