# Generated by Django 2.2.6 on 2020-07-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0021_auto_20200729_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='hash_id',
            field=models.TextField(default='208b1579-ba1a-4a97-8e39-507604382d7b', unique=True),
        ),
        migrations.AlterField(
            model_name='ticketraffle',
            name='code',
            field=models.TextField(default='3FYG7A', unique=True),
        ),
    ]
