# Generated by Django 2.2.6 on 2020-07-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0022_auto_20200729_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='hash_id',
            field=models.TextField(default='cf441f37-cae2-4b30-a19e-c2b290dcc3e6', unique=True),
        ),
        migrations.AlterField(
            model_name='ticketraffle',
            name='code',
            field=models.TextField(default='JWGR7N', unique=True),
        ),
    ]
