# Generated by Django 2.2.6 on 2021-01-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0024_auto_20200729_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='hash_id',
            field=models.TextField(default='a8e0f4f2-57fb-433c-8674-2c748bdbb79b', unique=True),
        ),
        migrations.AlterField(
            model_name='ticketraffle',
            name='code',
            field=models.TextField(default='3HBFWC', unique=True),
        ),
    ]
