# Generated by Django 2.2.6 on 2020-07-09 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200709_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 9, 12, 39, 17, 751304)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='hash_id',
            field=models.TextField(default='38eda532-3121-4c54-a0e7-a3fbc49a430f', unique=True),
        ),
    ]
