# Generated by Django 2.2.6 on 2020-07-09 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200709_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 9, 12, 42, 14, 562301)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='hash_id',
            field=models.TextField(default='63fd2485-77f4-4aee-a2a5-e6db3d20811b', unique=True),
        ),
    ]
