# Generated by Django 2.2.6 on 2020-07-09 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200709_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 9, 13, 38, 42, 604522)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='hash_id',
            field=models.TextField(default='34d686bd-a31d-4655-941b-b923e6963708', unique=True),
        ),
    ]
