# Generated by Django 2.2.6 on 2020-07-09 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20200709_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 9, 14, 5, 20, 668177)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='hash_id',
            field=models.TextField(default='a24d8437-9f45-4954-8574-9712fdaba0fe', unique=True),
        ),
    ]
