# Generated by Django 2.2.6 on 2020-07-16 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20200716_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 18, 15, 35, 182764)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='hash_id',
            field=models.TextField(default='ba950d9d-9356-4b58-b908-343ac25647c4', unique=True),
        ),
    ]
