# Generated by Django 2.2.6 on 2020-07-16 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20200716_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 18, 20, 22, 149676)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='hash_id',
            field=models.TextField(default='9a2ead65-2288-425f-b65f-4791b56dac50', unique=True),
        ),
    ]
