# Generated by Django 2.2.6 on 2020-07-16 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20200716_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 18, 20, 47, 896170)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='hash_id',
            field=models.TextField(default='f53a8cbd-00a2-4eb6-aa87-041ce542c9f1', unique=True),
        ),
    ]
