# Generated by Django 2.2.6 on 2020-07-16 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20200716_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 18, 59, 40, 676351)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='hash_id',
            field=models.TextField(default='e8272ca3-2b29-4d22-b716-2d05c00e3476', unique=True),
        ),
    ]
