# Generated by Django 2.2.6 on 2020-07-16 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20200716_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 19, 8, 20, 127906)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='hash_id',
            field=models.TextField(default='71dc55da-b9d8-4074-a1f5-eb71b1eff2f2', unique=True),
        ),
    ]
