# Generated by Django 2.2.6 on 2020-07-16 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20200716_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 19, 10, 12, 563745)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='hash_id',
            field=models.TextField(default='8b71e8a1-8dc6-4827-adc9-795f6579176b', unique=True),
        ),
    ]
