# Generated by Django 2.2.6 on 2020-07-16 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20200716_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 19, 10, 17, 553476)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='hash_id',
            field=models.TextField(default='30647f17-a8bf-47ea-962b-df3ec1ff1945', unique=True),
        ),
    ]
