# Generated by Django 2.2.6 on 2020-07-29 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_auto_20200729_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 29, 17, 21, 2, 6627)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='hash_id',
            field=models.TextField(default='e6152614-59a2-4949-9fd3-00a3ef042b9e', unique=True),
        ),
    ]
