# Generated by Django 2.2.6 on 2021-01-04 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_auto_20200729_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 4, 11, 18, 32, 58745)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='hash_id',
            field=models.TextField(default='210524ff-8312-4da9-9e52-951fac968d61', unique=True),
        ),
    ]
