# Generated by Django 2.2.6 on 2020-07-16 19:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0019_auto_20200716_1912'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Empresa'},
        ),
        migrations.AddField(
            model_name='profile',
            name='tickets',
            field=models.ManyToManyField(to='offer.TicketRaffle'),
        ),
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.IntegerField(default=1, help_text='Código da Empresa', unique=True, verbose_name='Código da Empresa'),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.UUIDField(default='722ecc2c-9ccb-4439-b9d2-42e8ee5a7844', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='América Burger', help_text='Nome da Empresa', max_length=40, verbose_name='Nome da Empresa'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 19, 12, 52, 19401), verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Company'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cpf',
            field=models.CharField(blank=True, help_text='Cpf do usuário', max_length=11, null=True, verbose_name='CPF do usuário'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hash_id',
            field=models.TextField(default='fdd88962-5f6d-414d-94ca-0fc66585c6ad', unique=True, verbose_name='ID Unico do Usuário'),
        ),
        migrations.AlterModelTable(
            name='company',
            table='people_company',
        ),
    ]
