# Generated by Django 2.2.6 on 2020-07-29 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20200729_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 29, 15, 16, 19, 984895), verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hash_id',
            field=models.TextField(default='29a44e55-a115-4412-810c-59bed79a7aaf', unique=True, verbose_name='ID Unico do Usuário'),
        ),
    ]
