# Generated by Django 2.2.6 on 2020-07-29 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20200729_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 29, 17, 19, 7, 834173), verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hash_id',
            field=models.TextField(default='dfec54c9-a2cf-41f4-bad7-e1d8152342d5', unique=True, verbose_name='ID Unico do Usuário'),
        ),
    ]
