# Generated by Django 2.2.6 on 2020-07-29 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20200729_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 29, 17, 21, 1, 890942), verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hash_id',
            field=models.TextField(default='c49f5c1e-9e14-4820-ae9b-74e4ebea700e', unique=True, verbose_name='ID Unico do Usuário'),
        ),
    ]
