# Generated by Django 2.2.6 on 2021-01-04 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_auto_20200729_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 4, 11, 18, 30, 973747), verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hash_id',
            field=models.TextField(default='29b6ffaa-9ba8-4ac6-b398-2394c4d72693', unique=True, verbose_name='ID Unico do Usuário'),
        ),
    ]
