# Generated by Django 2.2.6 on 2020-05-24 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(help_text='Nome de Rua, Avenida, Rodovia', max_length=200, verbose_name='Nome da Rua')),
                ('cep', models.CharField(help_text='Cep da Rua, Avenida, Rodovia', max_length=12, verbose_name='CEP')),
                ('number', models.IntegerField(help_text='Numero da Rua, Avenida, Rodovia', verbose_name='Número da Rua')),
                ('city', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='state.City')),
            ],
            options={
                'verbose_name': 'Endereço',
                'db_table': 'add_address',
            },
        ),
    ]
